name: Matrix
on: pull_request     #Actually it is push but just to stop it working each time I make a push I changed it to pull request.

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [6, 8, 10]
        include:
          - os: ubuntu-latest
            node-version: 8
            is_ubuntu_8: "true"
        exclude:
          - os: ubuntu-latest
            node-version: 6
          - os: macos-latest
            node-version: 8
    runs-on: ${{ matrix.os }}
    env:
      is_ubuntu_8: ${{ matrix.is_ubuntu_8 }}
    steps:
      - name: Log node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Log node version
        run: |
          node -v
          echo $is_ubuntu_8